package frc.robot.subsystems;

import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.RotationsPerSecond;

import java.util.Optional;
import java.util.function.Supplier;

import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import choreo.trajectory.SwerveSample;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.constants.TunerConstants;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Drivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> implements Subsystem {

    private double MaxSpeed = 1.0 * TunerConstants.kSpeedAt12Volts.in(MetersPerSecond); // kSpeedAt12Volts desired top speed
    private double MaxAngularRate = RotationsPerSecond.of(0.8).in(RadiansPerSecond); // 3/4 of a rotation per second max angular velocity

    public enum DriveState{
        STOP,
        IDLE,
        AUTO,
        BRAKE,
        DRIVE_JOYSTICKS,
        DRIVE_JOYSTICKS_SLOW,
        DRIVE_PIDTOPOSE,
        DRIVE_PIDTOANGLE,
        DRIVE_PIDTOANGLE_JOYSTICKS
    }

    private DriveState state = DriveState.DRIVE_JOYSTICKS;

    private CommandXboxController joystick;

    private Pose2d targetPose = new Pose2d();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final PIDController xController = new PIDController(2.0, 0.0, 0.1);
    private final PIDController yController = new PIDController(2.0, 0.0, 0.1);
    private final PIDController headingController = new PIDController(3.0, 0.0, 0.1);

    private final PIDController xControllerChoreo = new PIDController(3.0, 0.0, 0.1);
    private final PIDController yControllerChoreo = new PIDController(3.0, 0.0, 0.1);
    private final PIDController headingControllerChoreo = new PIDController(4, 0.0, 0.1);

    private final SwerveRequest.FieldCentric joystickDrive = new SwerveRequest.FieldCentric()
        .withDeadband(MaxSpeed * 0.03).withRotationalDeadband(MaxAngularRate * 0.03)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    private final SwerveRequest.FieldCentricFacingAngle joystickDriveWithAngle = new SwerveRequest.FieldCentricFacingAngle()
        .withDeadband(MaxSpeed * 0.03).withHeadingPID(3.0, 0.0, 0.1)
        .withDriveRequestType(DriveRequestType.Velocity)
        .withSteerRequestType(SteerRequestType.Position);

    private final SwerveRequest.ApplyRobotSpeeds applyRobotRelativeSpeeds = 
        new SwerveRequest.ApplyRobotSpeeds()
            .withDriveRequestType(SwerveModule.DriveRequestType.Velocity)
            .withSteerRequestType(SwerveModule.SteerRequestType.Position);

    private final SwerveRequest.ApplyFieldSpeeds applyFieldRelativeSpeeds =
        new SwerveRequest.ApplyFieldSpeeds()
            .withDriveRequestType(DriveRequestType.Velocity)
            .withSteerRequestType(SteerRequestType.Position);

    private final SwerveRequest.SwerveDriveBrake XBrake = new SwerveRequest.SwerveDriveBrake();

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not
     * construct
     * the devices themselves. If they need the devices, they can access them
     * through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public Drivetrain(
            CommandXboxController joystick,
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules) {

            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, modules
            );

            this.joystick = joystick;

            headingController.enableContinuousInput(-Math.PI, Math.PI);
            headingController.setTolerance(0.025);
            xController.setTolerance(0.02);
            yController.setTolerance(0.02);

            headingControllerChoreo.enableContinuousInput(-Math.PI, Math.PI);
            headingControllerChoreo.setTolerance(0.1);
            xControllerChoreo.setTolerance(0.1);
            yControllerChoreo.setTolerance(0.1);
    }

    /**
     * Returns a command that applies the specified control request to this swerve
     * drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    public void setDriveState(DriveState wantedState) {
        state = wantedState;
    }

    public DriveState getDriveState() {
        return state;
    }

    public void setTargetPose(Pose2d wantedPose) {
        targetPose = wantedPose;
    }

    public Pose2d getTargetPose() {
        return targetPose;
    }

    public Pose2d getPose() {
        return this.getState().Pose;
    }

    private void runPIDToPose(Pose2d targetPose) {
            Pose2d currentPose = this.getPose();
            double vx = xController.calculate(currentPose.getX(), targetPose.getX());
            double vy = yController.calculate(currentPose.getY(), targetPose.getY());
            double vomega = headingController.calculate(currentPose.getRotation().getRadians(), targetPose.getRotation().getRadians());

            this.setControl(applyFieldRelativeSpeeds.withSpeeds(new ChassisSpeeds(vx, vy, vomega)));
    }

    private void runPIDToAngle(Rotation2d angle) {
            Rotation2d currentRot = this.getPose().getRotation();
            double vomega = headingController.calculate(currentRot.getRadians(), angle.getRadians());

            if (Math.abs(currentRot.relativeTo(angle).getDegrees()) < 2) {
                this.setControl(XBrake);
            } else {
                this.setControl(applyFieldRelativeSpeeds.withSpeeds(new ChassisSpeeds(0, 0, vomega)));
            }
    }

    public boolean atAngleToScore() {
        return Math.abs(this.getPose().getRotation().relativeTo(targetPose.getRotation()).getDegrees()) < 2;
    }

    @Override
    public void periodic() {

        Logger.recordOutput("Drivetrain/RobotRelativeSpeeds", this.getState().Speeds);
        Logger.recordOutput("Drivetrain/RobotPose", this.getState().Pose);

        Logger.recordOutput("Drivetrain/TargetPose", this.getTargetPose());
        Logger.recordOutput("Drivetrain/TargetRotation", this.getTargetPose().getRotation());
        Logger.recordOutput("Drivetrain/State", this.getDriveState());

        Logger.recordOutput("Drivetrain/PigeonYaw", this.getPigeon2().getYaw().getValueAsDouble());
        Logger.recordOutput("Drivetrain/PigeonRoll", this.getPigeon2().getRoll().getValueAsDouble());
        Logger.recordOutput("Drivetrain/PigeonPitch", this.getPigeon2().getPitch().getValueAsDouble());

        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                allianceColor == Alliance.Red
                ? kRedAlliancePerspectiveRotation
                : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        switch (state) {
            case STOP:
                this.setControl(applyRobotRelativeSpeeds.withSpeeds(new ChassisSpeeds(0, 0, 0)));
                break;

            case IDLE:
                break;

            case AUTO:
                break;

            case BRAKE:
                this.setControl(XBrake);
                break;

            case DRIVE_JOYSTICKS:
                this.setControl(
                    joystickDrive.withVelocityX(-joystick.getLeftY() * MaxSpeed) 
                    .withVelocityY(-joystick.getLeftX() * MaxSpeed) 
                    .withRotationalRate(-joystick.getRightX() * MaxAngularRate));
                break;
                
            case DRIVE_JOYSTICKS_SLOW:
                this.setControl(
                    joystickDrive.withVelocityX(-joystick.getLeftY() * MaxSpeed * 0.5) 
                    .withVelocityY(-joystick.getLeftX() * MaxSpeed * 0.5) 
                    .withRotationalRate(-joystick.getRightX() * MaxAngularRate * 0.5));
                break;

            case DRIVE_PIDTOANGLE:
                this.runPIDToAngle(targetPose.getRotation());
                break;

            case DRIVE_PIDTOANGLE_JOYSTICKS:
                this.setControl(
                    joystickDriveWithAngle.withVelocityX(-joystick.getLeftY() * MaxSpeed) 
                    .withVelocityY(-joystick.getLeftX() * MaxSpeed)
                    .withTargetDirection(targetPose.getRotation()));
                break;

            case DRIVE_PIDTOPOSE:
                this.runPIDToPose(targetPose);
                break;

            default:
                this.setControl(applyRobotRelativeSpeeds.withSpeeds(new ChassisSpeeds(0, 0, 0)));
                break;
        }
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision
     *                              camera.
     * @param timestampSeconds      The timestamp of the vision measurement in
     *                              seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the
     * odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the
     *                                 vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in
     *                                 seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose
     *                                 measurement
     *                                 in the form [x, y, theta]ᵀ, with units in
     *                                 meters and radians.
     */
    @Override
    public void addVisionMeasurement(
            Pose2d visionRobotPoseMeters,
            double timestampSeconds,
            Matrix<N3, N1> visionMeasurementStdDevs) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds),
                visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is
     *         empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void followTrajectory(SwerveSample sample) {
        state = DriveState.AUTO;

        // Get the current pose of the robot
        Pose2d pose = getPose();

        // Generate the next speeds for the robot
        ChassisSpeeds speeds = new ChassisSpeeds(
            sample.vx + xControllerChoreo.calculate(pose.getX(), sample.x),
            sample.vy + yControllerChoreo.calculate(pose.getY(), sample.y),
            sample.omega + headingControllerChoreo.calculate(pose.getRotation().getRadians(), sample.heading)
        );

        // Apply the generated speeds
        this.setControl(applyFieldRelativeSpeeds.withSpeeds(speeds));
    }
}